### ISSUE TITLE
Prioritize nodes without scores when refreshing bot scores

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-frontend#16]
_From @mihaivavram on April 5, 2018 15:2_

_Copied from original issue: IUNetSci/hoaxy-botometer#225_

**Comment by glciampaglia** [comment]
The priority queue has been implemented. Mihai pointed out that accounts that have been suspended will stay with no score even after we updated every node. What to do with them? We discussed and we agreed that this is not a real issue. If the user finds out, they will be able to click on the Twitter profile and see that the account has been suspended. On the other hand, we still want them in the queue since sometimes suspended accounts can be unsuspended by Twitter, and so it is still worth to check them, as they may come back. 

Right now, the suspended accounts will have higher priority. Ben pointed out that if they might still be at the top of the queue, then this could be a problem. @mihaivavram will check this to make sure, and close.

**Comment by mihaivavram** [comment]
I have confirmed that the "suspended accounts" will not be at the top of the queue with every request of "Update Bot Scores". Indeed after every query, the bot scores we do not have (because they have never been fetched before, or we tried but they were suspended) will be at the top of the queue, but with each passing "Update Bot Scores" request during a given visualization, other accounts in the queue will be obtained, e.g., stale accounts. This means that the update functionality will never get stuck on suspended accounts because the mechanism is really an index passing through a queue (top to bottom) instead of a queue changing. I believe we agreed this is expected and reasonable functionality, therefore, closing.
