### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-frontend#20]
Some of the information in the README (for example javascript libraries) is stale and should be updated to reflect the current state of the code.

**Comment by filmenczer** [comment]
Also, the old repo (https://github.iu.edu/truthy-team/hoaxy-website) should be archived. I added a note in the README that it is deprecated, but being there it can be confusing.

We also need to discuss the relationship between Main and Deployment branch, and find a way to document how to push Deployment to production. @benabus wrote: "Since the deployment branch is now located in the hoaxy-frontend repo, which is open sourced and public, how much deployment instruction do we want to keep there?  Where else should we host these instructions if we don’t want to make details public?"

I need simple (and easy to find) instructions in case I need to quickly revise something on the website.

**Comment by glciampaglia** [comment]
We archived Hoaxy-Website.

**Comment by benabus** [comment]
README is updated and I added a new file https://github.com/IUNetSci/hoaxy-frontend/blob/deployment/DEPLOYMENT_README.md with deployment instructions.
