### ISSUE TITLE
Check for Twitter authorization when search params are in URL string

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-frontend#29]
We just launched BEV (https://botometer.iuni.iu.edu/bev/) and need a bit of help with Hoaxy integration.

When one clicks on one of the entities, we want to launch a Hoaxy (Twitter) search. That works fine if the user has authorized Hoaxy with their Twitter account. But if not, instead of asking the user to authorize, Hoaxy gives an error. This is different from the case in which the user clicks the search button on the Hoaxy website, in which case the user is asked to authorize.

Would it be possible to do the authorization check when the search parameters are in the URL string? This way links to Hoaxy searches from other sites, like BEV, would work. This would make Hoaxy much more usable.

**Comment by benabus** [comment]
A quick investigation reveals that this is because of popup blocking.

Any popup that is not the result of direct user interaction will be blocked, including the twitter authorization popup.  When you go to a link with parameters, it tries to authenticate automatically, but the popup gets blocked and hoaxy returns an error.  Firefox has a big yellow “Popup prevented” banner.  Chrome just has this tiny little icon that indicates it was blocked.

When on the Hoaxy site, you have to actually click the search button before it asks to authenticate, so it works fine.

I’ll try to come up with an alternative solution today and will let you know what happens.

**Comment by benabus** [comment]
I updated Hoaxy so that instead of throwing an error, it has a green modal with a button to retry the query.  When you click the button, that counts as a user interaction, so it’ll popup the authentication window.   I think this is probably the best option.
