### ISSUE TITLE
Tweak the Botometer API query

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-frontend#31]
Now that the Botometer API queries are faster, we should revisit the decision of splitting the query into 3 parts. Maybe just one or at most 2 queries? The code should be flexible to take a parameter so that we can quickly change this based on traffic, if needed.

**Comment by filmenczer** [comment]
Possible policy: taking input n = number of queries

Loop over n-1 steps: at each step add 10%
In the last step: add all remaining nodes, if there are any

Example: 
n=1 ==> all at once (default)
n=2 ==> 10%, 90%
n=3 ==> 10%, 10%, 80%
etc...

**Comment by benabus** [comment]
There was already a setting that allows you to specify the number and sizes of the batches.  It didn't do any auto-tuning but let you specify the sizes in an array: `botcache_chunk_sizes = [50, 200, 1000];`

Since this already existed, I just changed the setting to one batch of 2000 (Twitter searches occasionally return 1030 or 1040 results.  Setting it to 2000 just means to get all of the scores at once.)

I moved this setting into the config.js file so that it would be easy to change later if we wanted to.
