### ISSUE TITLE
Reaching Twitter API limit

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-frontend#35]
We are getting this error; we should not, because we should be using the user's account API keys after authorization. We need to make sure this is implemented correctly; if the rate limit is application-level, we may be using the app's keys and therefore multiple user queries in the aggregate may be hitting the limit.

@mihaivavram in case you have time to look into this, please let us have your thoughts...

**Comment by benabus** [comment]
Looks like the problem was not app level authentication.

There's a recursive loop in there that will keep polling twitter over and over until we get 1000 nodes.  However, if for whatever reason (the topic is too new, for example) after 10 queries, there were only 50 nodes, it would keep going forever, hoping to find 1000 nodes.  This would eat up the user's search api limit.

I added in a check to limit the query to a maximum of 10 requests per search regardless of the number of nodes.  So, maximum of 10 requests or a maximum of 1000 nodes.  This will reduce the number of requests and prevent hitting the rate limit.

PS:  Rate limit at time of this writing is 180 requests per 15 minutes per user.  So this gets a max of 18 queries per 15 minutes.
