### ISSUE TITLE
Weighted Edges

### ISSUE THREAD

**Issue by benabus** [IUNetSci/hoaxy-frontend#63]
We could visualize the weights of the edges through thickness using a logarithmic scale.  The weight being the number of retweets/quotes/mentions/replies between the two accounts.

**Comment by marcmccarty** [comment]
The method can be put up for discussion, as well as the overall look/style, but the task is completed on live Hoaxy currently.

Code explanation:
`minEdgeSize` is 0.25 so that even log(1) = 0 will set the edge to 0.25 (a visible line)
`maxEdgeSize` is 2 because it's probably the thickest line that looks reasonable and it's unlikely that there will need to be a bigger comparison than 1 retweet to 100 retweets (up for discussion, of course).
`var edgeWeight = Math.log(Number(nodes[i].outgoing[j].count))` Log base 10 of the number of retweets (even if it's multiple retweets from the same user), basically.

Code:
```
      settings: {
		autoRescale: true,
		scalingMode: "inside",
                edgeHoverExtremities: true,
                borderSize: 1,
		minArrowSize: 6,
		minEdgeSize: 0.25,
		maxEdgeSize: 2,
...
					var edgeWeight = Math.log(Number(nodes[i].outgoing[j].count));
					graph.edges.push({
						id: "e" + edgeIndex,
						source: i,
						target: j,

						source_screenName: nodes[i].screenName,
						target_screenName: nodes[j].screenName,

						from_node_id: nodes_id[i],
						to_node_id: nodes_id[j],
						size: edgeWeight,
...
```

Examples:
![](https://i.imgur.com/M71oD6z.png)
![](https://i.imgur.com/PGp2bx0.png)
![](https://i.imgur.com/G6eJhp9.png)
![](https://i.imgur.com/Q6OZdNB.png)
